# Generated by Django 6.0.2 on 2026-02-21 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=120)),
                ('motto1', models.CharField(max_length=255)),
                ('motto2', models.CharField(blank=True, max_length=255)),
                ('likes', models.TextField(blank=True)),
                ('dislikes', models.TextField(blank=True)),
                ('gps_coordinates', models.CharField(blank=True, max_length=100)),
                ('enneagramtype1', models.IntegerField(choices=[(0, 'unknown'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, 'none')], default=0)),
                ('enneagramtype2', models.IntegerField(choices=[(0, 'unknown'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, 'none')], default=10)),
                ('registration_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TttResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=64)),
                ('ttt_type', models.CharField(max_length=4)),
                ('temperament', models.CharField(max_length=2)),
                ('ei', models.IntegerField(default=0)),
                ('sn', models.IntegerField(default=0)),
                ('tf', models.IntegerField(default=0)),
                ('jp', models.IntegerField(default=0)),
                ('taken_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rcd_sent', to=settings.AUTH_USER_MODEL)),
                ('to_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rcd_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('from_member', 'to_member'), name='unique_contact_request')],
            },
        ),
    ]
